const ROOMS_REQUEST_PENDING = 'ROOMS_REQUEST_PENDING';
const ROOMS_REQUEST_SUCCESS = 'ROOMS_REQUEST_SUCCESS';
const ROOMS_REQUEST_FAILED = 'ROOMS_REQUEST_FAILED';

const CURRENT_ROOM_REQUEST_SUCCESS = 'CURRENT_ROOM_REQUEST_SUCCESS';

const UPDATE_BOOKED_HISTORY = 'UPDATE_BOOKED_HISTORY';
const LOAD_BOOKED_HISTORY = 'LOAD_BOOKED_HISTORY';
const LOAD_ROOMS = 'LOAD_ROOMS';
const LOAD_ROOM_INFO = 'LOAD_ROOM_INFO';
const BOOK_ROOM = 'BOOK_ROOM';

export {
  ROOMS_REQUEST_PENDING,
  ROOMS_REQUEST_SUCCESS,
  ROOMS_REQUEST_FAILED,
  CURRENT_ROOM_REQUEST_SUCCESS,
  LOAD_ROOM_INFO,
  UPDATE_BOOKED_HISTORY,
  LOAD_BOOKED_HISTORY,
  LOAD_ROOMS,
  BOOK_ROOM,
};
