const ROOMS_REQUEST_PENDING = 'ROOMS_REQUEST_PENDING';
const ROOMS_REQUEST_SUCCESS = 'ROOMS_REQUEST_SUCCESS';
const ROOMS_REQUEST_FAILED = 'ROOMS_REQUEST_FAILED';

const CURRENT_ROOM_REQUEST_SUCCESS = 'CURRENT_ROOM_REQUEST_SUCCESS';

const LOAD_ROOMS = 'LOAD_ROOMS';
const LOAD_ROOM_INFO = 'LOAD_ROOM_INFO';

export {
  ROOMS_REQUEST_PENDING,
  ROOMS_REQUEST_SUCCESS,
  ROOMS_REQUEST_FAILED,
  LOAD_ROOMS,
  CURRENT_ROOM_REQUEST_SUCCESS,
  LOAD_ROOM_INFO,
};
